class WorldModesController < ApplicationController
  before_action :set_world_mode, only: [:show, :edit, :update, :destroy]

  def test_pixijs
    
  end

  def map_pixi
  
  end
  
  def map_anime
  end
  
  def map_anime2
  end
  
  def new_goal
  end
  
  def goal_details
  end
  
  def search_results
    @query = params[:search]
  end
  
  def map
    @goals = Goal.where(:status => "active")
  end
  
  def new_goal
    
  end

  def set_goal
    #insert params info into goals db
  end

  def details
    @goal = Goal.find(params[:id])
  end



  # BELOW WAS AUTOGENERATED

  # GET /world_modes
  # GET /world_modes.json
  def index
    @world_modes = WorldMode.all
  end

  # GET /world_modes/1
  # GET /world_modes/1.json
  def show
  end

  # GET /world_modes/new
  def new
    @world_mode = WorldMode.new
  end

  # GET /world_modes/1/edit
  def edit
  end

  # POST /world_modes
  # POST /world_modes.json
  def create
    @world_mode = WorldMode.new(world_mode_params)

    respond_to do |format|
      if @world_mode.save
        format.html { redirect_to @world_mode, notice: 'World mode was successfully created.' }
        format.json { render :show, status: :created, location: @world_mode }
      else
        format.html { render :new }
        format.json { render json: @world_mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /world_modes/1
  # PATCH/PUT /world_modes/1.json
  def update
    respond_to do |format|
      if @world_mode.update(world_mode_params)
        format.html { redirect_to @world_mode, notice: 'World mode was successfully updated.' }
        format.json { render :show, status: :ok, location: @world_mode }
      else
        format.html { render :edit }
        format.json { render json: @world_mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /world_modes/1
  # DELETE /world_modes/1.json
  def destroy
    @world_mode.destroy
    respond_to do |format|
      format.html { redirect_to world_modes_url, notice: 'World mode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_world_mode
      @world_mode = WorldMode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def world_mode_params
      params.require(:world_mode).permit(:new)
    end
end
